[config]

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[templates.noctalia]
input_path = './template/noctalia.json'
output_path = '~/.config/noctalia/colors.json'

[templates.gtk3]
input_path = './template/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './template/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = './template/qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './template/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kcolorscheme]
input_path = './template/kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/matugen.colors'

[templates.ghostty]
input_path = './template/ghostty.toml'
output_path = '~/.config/ghostty/themes/matugen'
post_hook = "pkill -SIGUSR2 ghostty"

[templates.yazi]
input_path = './template/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.starship]
input_path = './template/starship.toml'
output_path = '~/.config/starship.toml'

[templates.helix]
input_path = './template/helix.toml'
output_path = '~/.config/helix/themes/matugen.toml'
