[config]

[templates.yazi]
input_path = './template/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.starship]
input_path = './template/starship.toml'
output_path = '~/.config/starship.toml'

[templates.helix]
input_path = './template/helix.toml'
output_path = '~/.config/helix/themes/matugen.toml'
